.zshrc,.zshrc
.zshrc.custom.i3,.zshrc.custom
.tmux.conf,.tmux.conf
.nethackrc,.nethackrc
.conkyrc,.conkyrc
.aliases,.aliases
.npmrc,.npmrc
.config/nvim,.config/nvim
.config/urxvt,.config/urxvt
.config/i3,.config/i3
.config/rofi,.config/rofi
.config/polybar,.config/polybar
.config/tmuxinator,.config/tmuxinator
.hushlogin,.hushlogin
.config/ghostty,.config/ghostty
.claude,.claude
